#!/bin/bash
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/anaconda-docs-2.0.25-0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/anaconda-docs-2020.02-0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/anaconda-docs-2020.04-0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/anaconda-oss-docs-2020.02-0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/anaconda-oss-docs-2020.04-0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/apispec-3.3.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/argcomplete-1.11.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/arviz-0.6.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/asgiref-3.2.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/asgiref-3.2.5-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/asgiref-3.2.7-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/atomicwrites-1.4.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/aws-requests-auth-0.4.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/black-19.10b0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/bleach-3.1.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/boto3-1.11.14-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/boto3-1.12.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/boto3-1.12.12-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/boto3-1.12.39-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/botocore-1.14.14-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/botocore-1.15.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/botocore-1.15.12-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/botocore-1.15.38-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/botocore-1.15.39-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/bs4-4.9.0-0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/cachetools-3.1.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/cattrs-1.0.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/celery-4.4.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/click-7.1.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/cloudpickle-1.3.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/cloudpickle-1.4.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/cloudpickle-1.4.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/configargparse-1.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/configparser-5.0.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/connexion-2.6.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/contextvars-2.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/coveralls-1.11.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/cppy-1.1.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/curio-1.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-2.10.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-2.10.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-2.11.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-2.12.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-2.13.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-2.14.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-2.15.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-core-2.10.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-core-2.10.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-core-2.11.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-core-2.12.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-core-2.13.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-core-2.14.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-core-2.15.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-image-0.2.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/dask-ml-1.2.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/datadog-0.35.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/datashader-0.10.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/decorator-4.4.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/deprecated-1.2.7-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/descartes-1.1.0-py_4.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/distributed-2.10.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/django-3.0.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/django-pyodbc-azure-2.1.0.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/elasticsearch-6.3.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/esda-2.2.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/faker-4.0.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/flask-1.1.1-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/flask-1.1.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/flask-json-0.3.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/freezegun-0.3.15-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/fsspec-0.6.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/fsspec-0.7.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/ftfy-5.7-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/func_timeout-4.3.5-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/gast-0.3.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/geoviews-1.6.6-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/geoviews-core-1.6.6-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/giddy-2.3.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/gitdb-4.0.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/gitpython-3.1.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/gitpython-3.1.1-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/google-auth-1.11.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/google-auth-1.13.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/google-auth-1.14.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/google-auth-oauthlib-0.4.1-py_2.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/google-cloud-core-1.3.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/google-cloud-storage-1.27.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/google-cloud-storage-1.28.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/google-pasta-0.2.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/google-resumable-media-0.5.0-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/holoviews-1.13.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/holoviews-1.13.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/holoviews-1.13.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/hypothesis-5.4.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/hypothesis-5.5.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/hypothesis-5.8.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/icalendar-4.0.5-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/idna-2.9-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/ijson-2.6.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/ijson-3.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/ijson-3.0.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/imageio-2.8.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/inequality-1.0.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/intake-0.5.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jaraco.classes-3.1.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jaraco.collections-3.0.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jaraco.functools-3.0.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jaraco.itertools-5.0.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jeepney-0.4.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jinja2-2.11.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jinja2-2.11.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/json5-0.9.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/json5-0.9.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/json5-0.9.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/json5-0.9.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/json5-0.9.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jsonlines-1.2.0-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jsonpatch-1.24-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jsonpickle-1.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jsonpickle-1.4.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jsonpointer-2.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jupyter_client-6.0.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jupyter_client-6.1.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jupyter_client-6.1.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jupyter_client-6.1.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jupyter_console-6.1.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jupyter_telemetry-0.0.5-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jupyterlab-1.2.6-pyhf63ae98_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jupyterlab_server-0.3.4-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jupyterlab_server-1.0.7-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jupyterlab_server-1.1.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/jupyterlab_server-1.1.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/keras-preprocessing-1.1.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/libpysal-4.2.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/locustio-0.14.5-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/locustio-0.14.6-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/mako-1.1.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/mako-1.1.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/mando-0.6.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/mapclassify-2.2.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/marshmallow-3.5.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/mgwr-2.1.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/mock-4.0.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/mock-4.0.1-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/mock-4.0.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/more-itertools-8.2.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/mypy-0.770-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/natsort-7.0.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/nbformat-5.0.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/nbsmoke-0.4.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/nose-exclude-0.5.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/nose-parameterized-0.6.0-pyh91ea838_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/openpyxl-3.0.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/owslib-0.19.2-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/packaging-20.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/packaging-20.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/panel-0.8.0-0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/panel-0.9.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/panel-0.9.5-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/param-1.9.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/paramiko-2.7.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/paramiko-2.7.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/parso-0.6.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/parso-0.6.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/parso-0.6.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/parso-0.7.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pathspec-0.7.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pg8000-1.15.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pims-0.4.1-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/plotly-4.5.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/plotly-4.5.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/plotly-4.6.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pointpats-2.1.0-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/prompt-toolkit-3.0.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/prompt_toolkit-3.0.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/prompt_toolkit-3.0.4-0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.20-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pyflakes-2.2.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pygments-2.6.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pymc3-3.8-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pynndescent-0.4.7-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.7-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pysal-2.2.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pyspark-2.4.5-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pytest-astropy-0.8.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pytest-astropy-header-0.1.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pytest-csv-2.0.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pytest-html-2.1.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pytest-mock-2.0.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pytest-mock-3.0.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pytest-openfiles-0.5.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pytest-ordering-0.6-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pytest-replay-1.2.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pytest-rerunfailures-8.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pytest-rerunfailures-9.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pytest-timeout-1.3.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pytest-xdist-1.31.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/python-fastjsonschema-2.14.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/python-json-logger-0.1.11-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/python-jsonrpc-server-0.3.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/python-libarchive-c-2.9-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/python3-saml-1.9.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pytz-2020.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pyutilib-5.8.0-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pyviz_comms-0.7.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/pyviz_comms-0.7.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/qdarkstyle-2.8-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/qdarkstyle-2.8.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/qtawesome-0.6.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/qtawesome-0.7.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/qtconsole-4.7.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/qtconsole-4.7.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/qtconsole-4.7.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/radon-4.1.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/rasterstats-0.14.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/redis-py-3.4.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/rope-0.16.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/rsa-4.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/scramp-1.1.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/seaborn-0.10.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/seaborn-0.10.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/segregation-1.2.0-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/setuptools-rust-0.10.6-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/setuptools-scm-3.5.0-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/setuptools_scm-3.4.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/setuptools_scm-3.5.0-1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/slicerator-0.9.8-py_1.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/slicerator-1.0.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/smart_open-1.11.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/smmap-3.0.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/smmap-3.0.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/soupsieve-2.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/spaghetti-1.4.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/spaghetti-1.4.2.post2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/spglm-1.0.7-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/sphinx-2.4.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/sphinx-2.4.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/sphinx-3.0.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/sphinxcontrib-applehelp-1.0.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/sphinxcontrib-devhelp-1.0.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/sphinxcontrib-htmlhelp-1.0.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/sphinxcontrib-qthelp-1.0.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/sphinxcontrib-serializinghtml-1.1.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/sphinxcontrib-websupport-1.2.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/sphinxcontrib-websupport-1.2.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/spint-1.0.6-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/splot-1.1.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/spreg-1.0.4-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/spreg-1.1.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/spvcm-0.3.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/spyder_parso_requirement-1.0-0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/sqlparse-0.3.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/sshpubkeys-3.1.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/tempora-3.0.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/tensorboard-2.1.0-py2_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/tensorboard-2.1.0-py3_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/tensorflow-estimator-2.1.0-pyhd54b08b_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/tensorflow-hub-0.8.0-pyhe6710b0_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/text-unidecode-1.2-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/tobler-0.2.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/tqdm-4.42.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/tqdm-4.42.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/tqdm-4.43.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/tqdm-4.44.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/tqdm-4.45.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/tqdm-4.46.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/treelib-1.5.5-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/treelib-1.6.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/waitress-1.4.3-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.1.8-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.1.9-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/webob-1.8.6-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/werkzeug-0.16.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/werkzeug-1.0.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/werkzeug-1.0.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/xarray-0.15.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/xarray-0.15.1-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/xlsxwriter-1.2.8-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/zict-2.0.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/zipp-2.1.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/zipp-2.2.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
wget --connect-timeout=2 --tries=3 -N https://repo.anaconda.com/pkgs/main/noarch/zipp-3.1.0-py_0.tar.bz2 -P /fsrepo/stage/conda/pkgs/main/noarch/
